# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recommendation_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RecommendationWindow(object):
    def setupUi(self, RecommendationWindow):
        RecommendationWindow.setObjectName("RecommendationWindow")
        RecommendationWindow.resize(333, 196)
        self.centralwidget = QtWidgets.QWidget(RecommendationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 311, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rec_lbl_header = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.rec_lbl_header.setFont(font)
        self.rec_lbl_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rec_lbl_header.setObjectName("rec_lbl_header")
        self.verticalLayout.addWidget(self.rec_lbl_header)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.rec_lbl_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rec_lbl_1.setFont(font)
        self.rec_lbl_1.setObjectName("rec_lbl_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rec_lbl_1)
        self.rec_lbl_title1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rec_lbl_title1.setObjectName("rec_lbl_title1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rec_lbl_title1)
        self.rec_lbl_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rec_lbl_2.setFont(font)
        self.rec_lbl_2.setObjectName("rec_lbl_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rec_lbl_2)
        self.rec_lbl_title2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rec_lbl_title2.setObjectName("rec_lbl_title2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rec_lbl_title2)
        self.rec_lbl_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rec_lbl_3.setFont(font)
        self.rec_lbl_3.setObjectName("rec_lbl_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rec_lbl_3)
        self.rec_lbl_title3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rec_lbl_title3.setObjectName("rec_lbl_title3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rec_lbl_title3)
        self.rec_lbl_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rec_lbl_4.setFont(font)
        self.rec_lbl_4.setObjectName("rec_lbl_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.rec_lbl_4)
        self.rec_lbl_title4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rec_lbl_title4.setObjectName("rec_lbl_title4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rec_lbl_title4)
        self.rec_lbl_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rec_lbl_5.setFont(font)
        self.rec_lbl_5.setObjectName("rec_lbl_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.rec_lbl_5)
        self.rec_lbl_title5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rec_lbl_title5.setObjectName("rec_lbl_title5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.rec_lbl_title5)
        self.verticalLayout.addLayout(self.formLayout)
        RecommendationWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RecommendationWindow)
        self.statusbar.setObjectName("statusbar")
        RecommendationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RecommendationWindow)
        QtCore.QMetaObject.connectSlotsByName(RecommendationWindow)

    def retranslateUi(self, RecommendationWindow):
        _translate = QtCore.QCoreApplication.translate
        RecommendationWindow.setWindowTitle(_translate("RecommendationWindow", "Anime Recommendations"))
        self.rec_lbl_header.setText(_translate("RecommendationWindow", "Top 5 Recommended for You"))
        self.rec_lbl_1.setText(_translate("RecommendationWindow", "1)"))
        self.rec_lbl_title1.setText(_translate("RecommendationWindow", "TextLabel"))
        self.rec_lbl_2.setText(_translate("RecommendationWindow", "2)"))
        self.rec_lbl_title2.setText(_translate("RecommendationWindow", "TextLabel"))
        self.rec_lbl_3.setText(_translate("RecommendationWindow", "3)"))
        self.rec_lbl_title3.setText(_translate("RecommendationWindow", "TextLabel"))
        self.rec_lbl_4.setText(_translate("RecommendationWindow", "4)"))
        self.rec_lbl_title4.setText(_translate("RecommendationWindow", "TextLabel"))
        self.rec_lbl_5.setText(_translate("RecommendationWindow", "5)"))
        self.rec_lbl_title5.setText(_translate("RecommendationWindow", "TextLabel"))

